command_timeout=1000

format = """
$username\
$hostname\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$kubernetes\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[kubernetes]
disabled=false
format='[$symbol$context( \($namespace\))]($style) '

[git_branch]
style="bold purple"

[character]
success_symbol = "[❯](bold purple)[❯](bold blue)[❯](bold green)"
error_symbol =  "[✗](bold red)"
